language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
script:
    - python setup.py nosetests\w
branches:
    only:
        - master
        - develop
env:
  - TRAVIS_CI=true
after_success:
  - coveralls
