language: python
install:
  - pip install coveralls
python:
    - "2.7"
    - "3.3"
    - "3.4"
script:
    - python setup.py nosetests
branches:
    only:
        - master
        - develop
env:
  - TRAVIS_CI=true
after_success:
  - coveralls
